In [1]:
import pandas as pd
import os

In [2]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
os.getcwd()

'/Users/dhanaprakashdurairaj/Documents/GitHub/nba-player-analytics/Pre-processing/preprocessing_data'

In [4]:
# File to Load (Remember to change these)
player_stats_201617_data_to_load = "../../Resources/NBA Players Stats 201617.csv"
player_stats_201718_data_to_load = "../../Resources/NBA Players Stats 201718.csv"
player_stats_201819_data_to_load = "../../Resources/NBA Players Stats 201819.csv"
player_stats_201920_data_to_load = "../../Resources/NBA STATs19-20.csv"

player_salary_2019_to_present_data_to_load = "../../Resources/NBA_salaries_2019_present.csv"
player_salary_2016_to_2019_data_to_load = "../../Resources/nba_stats_salaries_16-19.csv"

print(player_stats_201617_data_to_load)
print(player_stats_201718_data_to_load)
print(player_stats_201819_data_to_load)
print(player_stats_201920_data_to_load)

print(player_salary_2016_to_2019_data_to_load)
print(player_salary_2019_to_present_data_to_load)

../../Resources/NBA Players Stats 201617.csv
../../Resources/NBA Players Stats 201718.csv
../../Resources/NBA Players Stats 201819.csv
../../Resources/NBA STATs19-20.csv
../../Resources/nba_stats_salaries_16-19.csv
../../Resources/NBA_salaries_2019_present.csv

In [5]:
print(os.path.isfile(player_stats_201617_data_to_load))
print(os.path.isfile(player_stats_201718_data_to_load))
print(os.path.isfile(player_stats_201819_data_to_load))
print(os.path.isfile(player_stats_201920_data_to_load))

print(os.path.isfile(player_salary_2016_to_2019_data_to_load))
print(os.path.isfile(player_salary_2019_to_present_data_to_load))

True
True
True
True
True
True

In [6]:
# Read the Player Stat and Salary Data
player_stats_201617_df = pd.read_csv(player_stats_201617_data_to_load)
player_stats_201718_df = pd.read_csv(player_stats_201718_data_to_load)
player_stats_201819_df = pd.read_csv(player_stats_201819_data_to_load)
player_stats_201920_df = pd.read_csv(player_stats_201920_data_to_load)

player_salary_2016_to_2019_df = pd.read_csv(player_salary_2016_to_2019_data_to_load)
player_salary_2019_to_present_df = pd.read_csv(player_salary_2019_to_present_data_to_load)

In [7]:
player_stats_201617_df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,√Ålex Abrines\abrinal01,SG,23,OKC,68,6,15.5,2.0,5.0,...,0.898,0.3,1.0,1.3,0.6,0.5,0.1,0.5,1.7,6.0
1,2,Quincy Acy\acyqu01,PF,26,TOT,38,1,14.7,1.8,4.5,...,0.750,0.5,2.5,3.0,0.5,0.4,0.4,0.6,1.8,5.8
2,2,Quincy Acy\acyqu01,PF,26,DAL,6,0,8.0,0.8,2.8,...,0.667,0.3,1.0,1.3,0.0,0.0,0.0,0.3,1.5,2.2
3,2,Quincy Acy\acyqu01,PF,26,BRK,32,1,15.9,2.0,4.8,...,0.754,0.6,2.8,3.3,0.6,0.4,0.5,0.6,1.8,6.5
4,3,Steven Adams\adamsst01,C,23,OKC,80,80,29.9,4.7,8.2,...,0.611,3.5,4.2,7.7,1.1,1.1,1.0,1.8,2.4,11.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,482,Cody Zeller\zelleco01,C,24,CHO,62,58,27.8,4.1,7.1,...,0.679,2.2,4.4,6.5,1.6,1.0,0.9,1.0,3.0,10.3
591,483,Tyler Zeller\zellety01,C,27,BOS,51,5,10.3,1.5,3.1,...,0.564,0.8,1.6,2.4,0.8,0.1,0.4,0.4,1.2,3.5
592,484,Stephen Zimmerman\zimmest01,C,20,ORL,19,0,5.7,0.5,1.6,...,0.600,0.6,1.3,1.8,0.2,0.1,0.3,0.2,0.9,1.2
593,485,Paul Zipser\zipsepa01,SF,22,CHI,44,18,19.2,2.0,5.0,...,0.775,0.3,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5
594,486,Ivica Zubac\zubaciv01,C,19,LAL,38,11,16.0,3.3,6.3,...,0.653,1.1,3.1,4.2,0.8,0.4,0.9,0.8,1.7,7.5

In [8]:
player_stats_201617_df.count()

Rk        595
Player    595
Pos       595
Age       595
Tm        595
G         595
GS        595
MP        595
FG        595
FGA       595
FG%       593
3P        595
3PA       595
3P%       549
2P        595
2PA       595
2P%       590
eFG%      593
FT        595
FTA       595
FT%       571
ORB       595
DRB       595
TRB       595
AST       595
STL       595
BLK       595
TOV       595
PF        595
PTS       595
dtype: int64

In [9]:
len(player_stats_201617_df["Player"])

595

In [10]:
len(player_stats_201617_df["Player"].unique())

486

In [11]:
player_stats_201617_df.isnull().sum()

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        2
3P         0
3PA        0
3P%       46
2P         0
2PA        0
2P%        5
eFG%       2
FT         0
FTA        0
FT%       24
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
dtype: int64

In [15]:
player_stats_201617_df.describe()

,Rk,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
count,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,593.000000,595.000000,595.000000,...,571.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000
mean,244.085714,26.411765,48.431933,22.136134,19.536471,3.034622,6.733445,0.441282,0.762857,2.169244,...,0.737637,0.825378,2.668067,3.490756,1.753950,0.608403,0.390924,1.080504,1.674286,8.186387
std,140.572151,4.261273,26.306597,27.427160,8.841753,2.080916,4.373783,0.102820,0.740244,1.892715,...,0.150574,0.761452,1.796496,2.425385,1.696807,0.409397,0.476857,0.768437,0.756984,5.842241
min,1.000000,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,124.500000,23.000000,24.000000,0.000000,12.700000,1.500000,3.600000,0.400000,0.200000,0.600000,...,0.667000,0.300000,1.400000,1.800000,0.600000,0.300000,0.100000,0.500000,1.150000,4.200000
50%,244.000000,26.000000,55.000000,8.000000,18.800000,2.500000,5.600000,0.442000,0.600000,1.800000,...,0.765000,0.600000,2.300000,2.900000,1.200000,0.500000,0.300000,0.900000,1.600000,6.600000
75%,364.500000,29.000000,73.000000,39.000000,26.300000,4.100000,8.900000,0.485000,1.200000,3.400000,...,0.833000,1.100000,3.400000,4.600000,2.300000,0.800000,0.500000,1.450000,2.200000,10.700000
max,486.000000,40.000000,82.000000,82.000000,37.800000,10.300000,24.000000,1.000000,4.100000,10.000000,...,1.000000,4.300000,10.300000,14.100000,11.200000,2.000000,6.000000,5.700000,4.400000,31.600000

In [16]:
player_stats_201617_df.dtypes

Rk          int64
Player     object
Pos        object
Age         int64
Tm         object
G           int64
GS          int64
MP        float64
FG        float64
FGA       float64
FG%       float64
3P        float64
3PA       float64
3P%       float64
2P        float64
2PA       float64
2P%       float64
eFG%      float64
FT        float64
FTA       float64
FT%       float64
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

In [19]:
player_stats_201617_df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,√Ålex Abrines\abrinal01,SG,23,OKC,68,6,15.5,2.0,5.0,...,0.898,0.3,1.0,1.3,0.6,0.5,0.1,0.5,1.7,6.0
1,2,Quincy Acy\acyqu01,PF,26,TOT,38,1,14.7,1.8,4.5,...,0.750,0.5,2.5,3.0,0.5,0.4,0.4,0.6,1.8,5.8
2,2,Quincy Acy\acyqu01,PF,26,DAL,6,0,8.0,0.8,2.8,...,0.667,0.3,1.0,1.3,0.0,0.0,0.0,0.3,1.5,2.2
3,2,Quincy Acy\acyqu01,PF,26,BRK,32,1,15.9,2.0,4.8,...,0.754,0.6,2.8,3.3,0.6,0.4,0.5,0.6,1.8,6.5
4,3,Steven Adams\adamsst01,C,23,OKC,80,80,29.9,4.7,8.2,...,0.611,3.5,4.2,7.7,1.1,1.1,1.0,1.8,2.4,11.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,482,Cody Zeller\zelleco01,C,24,CHO,62,58,27.8,4.1,7.1,...,0.679,2.2,4.4,6.5,1.6,1.0,0.9,1.0,3.0,10.3
591,483,Tyler Zeller\zellety01,C,27,BOS,51,5,10.3,1.5,3.1,...,0.564,0.8,1.6,2.4,0.8,0.1,0.4,0.4,1.2,3.5
592,484,Stephen Zimmerman\zimmest01,C,20,ORL,19,0,5.7,0.5,1.6,...,0.600,0.6,1.3,1.8,0.2,0.1,0.3,0.2,0.9,1.2
593,485,Paul Zipser\zipsepa01,SF,22,CHI,44,18,19.2,2.0,5.0,...,0.775,0.3,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5
594,486,Ivica Zubac\zubaciv01,C,19,LAL,38,11,16.0,3.3,6.3,...,0.653,1.1,3.1,4.2,0.8,0.4,0.9,0.8,1.7,7.5

In [20]:
player_stats_201617_df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,√Ålex Abrines\abrinal01,SG,23,OKC,68,6,15.5,2.0,5.0,...,0.898,0.3,1.0,1.3,0.6,0.5,0.1,0.5,1.7,6.0
1,2,Quincy Acy\acyqu01,PF,26,TOT,38,1,14.7,1.8,4.5,...,0.750,0.5,2.5,3.0,0.5,0.4,0.4,0.6,1.8,5.8
2,2,Quincy Acy\acyqu01,PF,26,DAL,6,0,8.0,0.8,2.8,...,0.667,0.3,1.0,1.3,0.0,0.0,0.0,0.3,1.5,2.2
3,2,Quincy Acy\acyqu01,PF,26,BRK,32,1,15.9,2.0,4.8,...,0.754,0.6,2.8,3.3,0.6,0.4,0.5,0.6,1.8,6.5
4,3,Steven Adams\adamsst01,C,23,OKC,80,80,29.9,4.7,8.2,...,0.611,3.5,4.2,7.7,1.1,1.1,1.0,1.8,2.4,11.3

In [26]:
player_stats_201617_df.describe()

,Rk,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
count,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,593.000000,595.000000,595.000000,...,571.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000
mean,244.085714,26.411765,48.431933,22.136134,19.536471,3.034622,6.733445,0.441282,0.762857,2.169244,...,0.737637,0.825378,2.668067,3.490756,1.753950,0.608403,0.390924,1.080504,1.674286,8.186387
std,140.572151,4.261273,26.306597,27.427160,8.841753,2.080916,4.373783,0.102820,0.740244,1.892715,...,0.150574,0.761452,1.796496,2.425385,1.696807,0.409397,0.476857,0.768437,0.756984,5.842241
min,1.000000,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,124.500000,23.000000,24.000000,0.000000,12.700000,1.500000,3.600000,0.400000,0.200000,0.600000,...,0.667000,0.300000,1.400000,1.800000,0.600000,0.300000,0.100000,0.500000,1.150000,4.200000
50%,244.000000,26.000000,55.000000,8.000000,18.800000,2.500000,5.600000,0.442000,0.600000,1.800000,...,0.765000,0.600000,2.300000,2.900000,1.200000,0.500000,0.300000,0.900000,1.600000,6.600000
75%,364.500000,29.000000,73.000000,39.000000,26.300000,4.100000,8.900000,0.485000,1.200000,3.400000,...,0.833000,1.100000,3.400000,4.600000,2.300000,0.800000,0.500000,1.450000,2.200000,10.700000
max,486.000000,40.000000,82.000000,82.000000,37.800000,10.300000,24.000000,1.000000,4.100000,10.000000,...,1.000000,4.300000,10.300000,14.100000,11.200000,2.000000,6.000000,5.700000,4.400000,31.600000

In [27]:
player_stats_201617_df.dtypes

Rk          int64
Player     object
Pos        object
Age         int64
Tm         object
G           int64
GS          int64
MP        float64
FG        float64
FGA       float64
FG%       float64
3P        float64
3PA       float64
3P%       float64
2P        float64
2PA       float64
2P%       float64
eFG%      float64
FT        float64
FTA       float64
FT%       float64
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

In [37]:
# The follwoing section to remove null values
#create a new Dataframe which would hold clean data
player_stats_201617_clean_df = player_stats_201617_df

In [38]:
# Get the count of rows
player_stats_201617_clean_df.count()

Rk        595
Player    595
Pos       595
Age       595
Tm        595
G         595
GS        595
MP        595
FG        595
FGA       595
FG%       593
3P        595
3PA       595
3P%       549
2P        595
2PA       595
2P%       590
eFG%      593
FT        595
FTA       595
FT%       571
ORB       595
DRB       595
TRB       595
AST       595
STL       595
BLK       595
TOV       595
PF        595
PTS       595
dtype: int64

In [39]:
# get the count of null values in each column
player_stats_201617_clean_df.isnull().sum()

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        2
3P         0
3PA        0
3P%       46
2P         0
2PA        0
2P%        5
eFG%       2
FT         0
FTA        0
FT%       24
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
dtype: int64

In [40]:
#List the columns where NAN values needs to be replace with 0
player_stats_201617_clean_df[['FG%','3P%','2P%','eFG%','FT%']]

       FG%    3P%    2P%   eFG%    FT%
0    0.393  0.381  0.426  0.531  0.898
1    0.412  0.411  0.413  0.521  0.750
2    0.294  0.143  0.400  0.324  0.667
3    0.425  0.434  0.414  0.542  0.754
4    0.571  0.000  0.572  0.571  0.611
..     ...    ...    ...    ...    ...
590  0.571  0.000  0.572  0.571  0.679
591  0.494  0.000  0.497  0.494  0.564
592  0.323    NaN  0.323  0.323  0.600
593  0.398  0.333  0.451  0.473  0.775
594  0.529  0.000  0.536  0.529  0.653

[595 rows x 5 columns]

In [42]:
#summarize NAN count
player_stats_201617_clean_df[['FG%','3P%','2P%','eFG%','FT%']].isnull().sum()

FG%      2
3P%     46
2P%      5
eFG%     2
FT%     24
dtype: int64

In [47]:
#replace nulll values with 0
player_stats_201617_clean_df[['FG%','3P%','2P%','eFG%','FT%']] = player_stats_201617_clean_df[['FG%','3P%','2P%','eFG%','FT%']].fillna(value=0)

In [48]:
# check whether the null values are replaced in new dataframe
player_stats_201617_clean_df[['FG%','3P%','2P%','eFG%','FT%']].isnull().sum()

FG%     0
3P%     0
2P%     0
eFG%    0
FT%     0
dtype: int64

In [50]:
player_stats_201617_clean_df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,√Ålex Abrines\abrinal01,SG,23,OKC,68,6,15.5,2.0,5.0,...,0.898,0.3,1.0,1.3,0.6,0.5,0.1,0.5,1.7,6.0
1,2,Quincy Acy\acyqu01,PF,26,TOT,38,1,14.7,1.8,4.5,...,0.750,0.5,2.5,3.0,0.5,0.4,0.4,0.6,1.8,5.8
2,2,Quincy Acy\acyqu01,PF,26,DAL,6,0,8.0,0.8,2.8,...,0.667,0.3,1.0,1.3,0.0,0.0,0.0,0.3,1.5,2.2
3,2,Quincy Acy\acyqu01,PF,26,BRK,32,1,15.9,2.0,4.8,...,0.754,0.6,2.8,3.3,0.6,0.4,0.5,0.6,1.8,6.5
4,3,Steven Adams\adamsst01,C,23,OKC,80,80,29.9,4.7,8.2,...,0.611,3.5,4.2,7.7,1.1,1.1,1.0,1.8,2.4,11.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,482,Cody Zeller\zelleco01,C,24,CHO,62,58,27.8,4.1,7.1,...,0.679,2.2,4.4,6.5,1.6,1.0,0.9,1.0,3.0,10.3
591,483,Tyler Zeller\zellety01,C,27,BOS,51,5,10.3,1.5,3.1,...,0.564,0.8,1.6,2.4,0.8,0.1,0.4,0.4,1.2,3.5
592,484,Stephen Zimmerman\zimmest01,C,20,ORL,19,0,5.7,0.5,1.6,...,0.600,0.6,1.3,1.8,0.2,0.1,0.3,0.2,0.9,1.2
593,485,Paul Zipser\zipsepa01,SF,22,CHI,44,18,19.2,2.0,5.0,...,0.775,0.3,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5
594,486,Ivica Zubac\zubaciv01,C,19,LAL,38,11,16.0,3.3,6.3,...,0.653,1.1,3.1,4.2,0.8,0.4,0.9,0.8,1.7,7.5

In [ ]:
#########################
# The following section is for splitting player_id and Playname into two columns
#########################

In [52]:
# Find datatype for playName column
player_stats_201617_clean_df['Player'].dtypes

dtype('O')

In [71]:
# Put player name into a list
player_id_name = player_stats_201617_clean_df['Player'].tolist()

In [72]:
# Split the playid and name and list the rows which are not split into 2 parts  with \ as delimeter(either 1 or >2)
for name in player_id_name:
    print(name.split("\\"), len(name.split("\\")))

['√Ålex Abrines', 'abrinal01'] 2
['Quincy Acy', 'acyqu01'] 2
['Quincy Acy', 'acyqu01'] 2
['Quincy Acy', 'acyqu01'] 2
['Steven Adams', 'adamsst01'] 2
['Arron Afflalo', 'afflaar01'] 2
['Alexis Ajin√ßa', 'ajincal01'] 2
['Cole Aldrich', 'aldrico01'] 2
['LaMarcus Aldridge', 'aldrila01'] 2
['Lavoy Allen', 'allenla01'] 2
['Tony Allen', 'allento01'] 2
['Al-Farouq Aminu', 'aminual01'] 2
['Chris Andersen', 'anderch01'] 2
['Alan Anderson', 'anderal01'] 2
['Justin Anderson', 'anderju01'] 2
['Justin Anderson', 'anderju01'] 2
['Justin Anderson', 'anderju01'] 2
['Kyle Anderson', 'anderky01'] 2
['Ryan Anderson', 'anderry01'] 2
['Giannis Antetokounmpo', 'antetgi01'] 2
['Carmelo Anthony', 'anthoca01'] 2
['Joel Anthony', 'anthojo01'] 2
['Trevor Ariza', 'arizatr01'] 2
['Darrell Arthur', 'arthuda01'] 2
['√ñmer A≈üƒ±k', 'asikom01'] 2
['D.J. Augustin', 'augusdj01'] 2
['Luke Babbitt', 'babbilu01'] 2
['Ron Baker', 'bakerro01'] 2
['Wade Baldwin', 'baldwwa01'] 2
['Leandro Barbosa', 'barbole01'] 2
['J.J. Barea', 'bareajo01'] 2
['Harrison Barnes', 'barneha02'] 2
['Matt Barnes', 'barnema02'] 2
['Matt Barnes', 'barnema02'] 2
['Matt Barnes', 'barnema02'] 2
['Will Barton', 'bartowi01'] 2
['Brandon Bass', 'bassbr01'] 2
['Nicolas Batum', 'batumni01'] 2
['Jerryd Bayless', 'bayleje01'] 2
['Aron Baynes', 'baynear01'] 2
['Kent Bazemore', 'bazemke01'] 2
['Bradley Beal', 'bealbr01'] 2
['Malik Beasley', 'beaslma01'] 2
['Michael Beasley', 'beaslmi01'] 2
['Marco Belinelli', 'belinma01'] 2
["DeAndre' Bembry", 'bembrde01'] 2
['Dragan Bender', 'bendedr01'] 2
['Anthony Bennett', 'bennean01'] 2
['Ben Bentil', 'bentibe01'] 2
['DƒÅvis BertƒÅns', 'bertada01'] 2
['Patrick Beverley', 'beverpa01'] 2
['Bismack Biyombo', 'biyombi01'] 2
['Nemanja Bjelica', 'bjeline01'] 2
['Tarik Black', 'blackta01'] 2
['Eric Bledsoe', 'bledser01'] 2
['Bojan Bogdanoviƒá', 'bogdabo02'] 2
['Bojan Bogdanoviƒá', 'bogdabo02'] 2
['Bojan Bogdanoviƒá', 'bogdabo02'] 2
['Andrew Bogut', 'bogutan01'] 2
['Andrew Bogut', 'bogutan01'] 2
['Andrew Bogut', 'bogutan01'] 2
['Joel Bolomboy', 'bolomjo01'] 2
['Devin Booker', 'bookede01'] 2
['Trevor Booker', 'booketr01'] 2
['Avery Bradley', 'bradlav01'] 2
['Corey Brewer', 'breweco01'] 2
['Corey Brewer', 'breweco01'] 2
['Corey Brewer', 'breweco01'] 2
['Malcolm Brogdon', 'brogdma01'] 2
['Aaron Brooks', 'brookaa01'] 2
['Anthony Brown', 'brownan02'] 2
['Anthony Brown', 'brownan02'] 2
['Anthony Brown', 'brownan02'] 2
['Bobby Brown', 'brownbo02'] 2
['Jaylen Brown', 'brownja02'] 2
['Nicol√°s Brussino', 'brussni01'] 2
['Reggie Bullock', 'bullore01'] 2
['Trey Burke', 'burketr01'] 2
['Alec Burks', 'burksal01'] 2
['Jimmy Butler', 'butleji01'] 2
['Bruno Caboclo', 'cabocbr01'] 2
['Jos√© Calder√≥n', 'caldejo01'] 2
['Jos√© Calder√≥n', 'caldejo01'] 2
['Jos√© Calder√≥n', 'caldejo01'] 2
['Kentavious Caldwell-Pope', 'caldwke01'] 2
['Isaiah Canaan', 'canaais01'] 2
['Clint Capela', 'capelca01'] 2
['DeMarre Carroll', 'carrode01'] 2
['Vince Carter', 'cartevi01'] 2
['Michael Carter-Williams', 'cartemi01'] 2
['Omri Casspi', 'casspom01'] 2
['Omri Casspi', 'casspom01'] 2
['Omri Casspi', 'casspom01'] 2
['Omri Casspi', 'casspom01'] 2
['Willie Cauley-Stein', 'caulewi01'] 2
['Tyson Chandler', 'chandty01'] 2
['Wilson Chandler', 'chandwi01'] 2
['Marquese Chriss', 'chrisma01'] 2
['Rakeem Christmas', 'chrisra01'] 2
['Semaj Christon', 'chrisse01'] 2
['Ian Clark', 'clarkia01'] 2
['Jordan Clarkson', 'clarkjo01'] 2
['Norris Cole', 'coleno01'] 2
['Darren Collison', 'collida01'] 2
['Nick Collison', 'collini01'] 2
['Mike Conley', 'conlemi01'] 2
['Pat Connaughton', 'connapa01'] 2
['Quinn Cook', 'cookqu01'] 2
['Quinn Cook', 'cookqu01'] 2
['Quinn Cook', 'cookqu01'] 2
['DeMarcus Cousins', 'couside01'] 2
['DeMarcus Cousins', 'couside01'] 2
['DeMarcus Cousins', 'couside01'] 2
['Robert Covington', 'covinro01'] 2
['Allen Crabbe', 'crabbal01'] 2
['Jamal Crawford', 'crawfja01'] 2
['Jordan Crawford', 'crawfjo02'] 2
['Jae Crowder', 'crowdja01'] 2
['Dante Cunningham', 'cunnida01'] 2
['Seth Curry', 'curryse01'] 2
['Stephen Curry', 'curryst01'] 2
['Troy Daniels', 'danietr01'] 2
['Anthony Davis', 'davisan02'] 2
['Deyonta Davis', 'davisde01'] 2
['Ed Davis', 'davised01'] 2
['Dewayne Dedmon', 'dedmode01'] 2
['Sam Dekker', 'dekkesa01'] 2
['Malcolm Delaney', 'delanma01'] 2
['Matthew Dellavedova', 'dellama01'] 2
['Luol Deng', 'denglu01'] 2
['DeMar DeRozan', 'derozde01'] 2
['Cheick Diallo', 'diallch01'] 2
['Boris Diaw', 'diawbo01'] 2
['Gorgui Dieng', 'dienggo01'] 2
['Spencer Dinwiddie', 'dinwisp01'] 2
['Toney Douglas', 'douglto01'] 2
['Goran Dragiƒá', 'dragigo01'] 2
['Andre Drummond', 'drumman01'] 2
['Jared Dudley', 'dudleja01'] 2
['Mike Dunleavy', 'dunlemi02'] 2
['Mike Dunleavy', 'dunlemi02'] 2
['Mike Dunleavy', 'dunlemi02'] 2
['Kris Dunn', 'dunnkr01'] 2
['Kevin Durant', 'duranke01'] 2
['Jarell Eddie', 'eddieja01'] 2
['Henry Ellenson', 'ellenhe01'] 2
['Wayne Ellington', 'ellinwa01'] 2
['Monta Ellis', 'ellismo01'] 2
['Joel Embiid', 'embiijo01'] 2
['James Ennis', 'ennisja01'] 2
['Tyler Ennis', 'ennisty01'] 2
['Tyler Ennis', 'ennisty01'] 2
['Tyler Ennis', 'ennisty01'] 2
['Tyreke Evans', 'evansty01'] 2
['Tyreke Evans', 'evansty01'] 2
['Tyreke Evans', 'evansty01'] 2
['Dante Exum', 'exumda01'] 2
['Kenneth Faried', 'farieke01'] 2
['Jordan Farmar', 'farmajo01'] 2
['Derrick Favors', 'favorde01'] 2
['Kay Felder', 'feldeka01'] 2
['Cristiano Fel√≠cio', 'feliccr01'] 2
['Raymond Felton', 'feltora01'] 2
['Yogi Ferrell', 'ferreyo01'] 2
['Yogi Ferrell', 'ferreyo01'] 2
['Yogi Ferrell', 'ferreyo01'] 2
['Dorian Finney-Smith', 'finnedo01'] 2
['Bryn Forbes', 'forbebr01'] 2
['Evan Fournier', 'fournev01'] 2
['Randy Foye', 'foyera01'] 2
['Tim Frazier', 'fraziti01'] 2
['Channing Frye', 'fryech01'] 2
['Danilo Gallinari', 'gallida01'] 2
['Langston Galloway', 'gallola01'] 2
['Langston Galloway', 'gallola01'] 2
['Langston Galloway', 'gallola01'] 2
['Patricio Garino', 'garinpa01'] 2
['Marc Gasol', 'gasolma01'] 2
['Pau Gasol', 'gasolpa01'] 2
['Rudy Gay', 'gayru01'] 2
['Michael Gbinije', 'gbinimi01'] 2
['Alonzo Gee', 'geeal01'] 2
['Paul George', 'georgpa01'] 2
['Marcus Georges-Hunt', 'georgma01'] 2
['Jonathan Gibson', 'gibsojo01'] 2
['Taj Gibson', 'gibsota01'] 2
['Taj Gibson', 'gibsota01'] 2
['Taj Gibson', 'gibsota01'] 2
['Manu Gin√≥bili', 'ginobma01'] 2
['Rudy Gobert', 'goberru01'] 2
['Archie Goodwin', 'goodwar01'] 2
['Archie Goodwin', 'goodwar01'] 2
['Archie Goodwin', 'goodwar01'] 2
['Aaron Gordon', 'gordoaa01'] 2
['Eric Gordon', 'gordoer01'] 2
['Marcin Gortat', 'gortama01'] 2
['Treveon Graham', 'grahatr01'] 2
['Jerami Grant', 'grantje01'] 2
['Jerami Grant', 'grantje01'] 2
['Jerami Grant', 'grantje01'] 2
['Jerian Grant', 'grantje02'] 2
['Danny Green', 'greenda02'] 2
['Draymond Green', 'greendr01'] 2
['Gerald Green', 'greenge01'] 2
['JaMychal Green', 'greenja01'] 2
['Jeff Green', 'greenje02'] 2
['Blake Griffin', 'griffbl01'] 2
['Justin Hamilton', 'hamilju01'] 2
['A.J. Hammons', 'hammoaj01'] 2
['Tim Hardaway Jr.', 'hardati02'] 2
['James Harden', 'hardeja01'] 2
['Maurice Harkless', 'harklma01'] 2
['Justin Harper', 'harpeju01'] 2
['Montrezl Harrell', 'harremo01'] 2
['Devin Harris', 'harride01'] 2
['Gary Harris', 'harriga01'] 2
['Joe Harris', 'harrijo01'] 2
['Manny Harris', 'harrima01'] 2
['Tobias Harris', 'harrito02'] 2
['Aaron Harrison', 'harriaa01'] 2
['Andrew Harrison', 'harrian01'] 2
['Udonis Haslem', 'hasleud01'] 2
['Spencer Hawes', 'hawessp01'] 2
['Spencer Hawes', 'hawessp01'] 2
['Spencer Hawes', 'hawessp01'] 2
['Gordon Hayward', 'haywago01'] 2
['Gerald Henderson', 'hendege02'] 2
['John Henson', 'hensojo01'] 2
['Juan Hernang√≥mez', 'hernaju01'] 2
['Willy Hernang√≥mez', 'hernawi01'] 2
['Mario Hezonja', 'hezonma01'] 2
['Roy Hibbert', 'hibbero01'] 2
['Roy Hibbert', 'hibbero01'] 2
['Roy Hibbert', 'hibbero01'] 2
['Buddy Hield', 'hieldbu01'] 2
['Buddy Hield', 'hieldbu01'] 2
['Buddy Hield', 'hieldbu01'] 2
['Nen√™', 'hilarne01'] 2
['George Hill', 'hillge01'] 2
['Jordan Hill', 'hilljo01'] 2
['Solomon Hill', 'hillso01'] 2
['Darrun Hilliard', 'hillida01'] 2
['Jrue Holiday', 'holidjr01'] 2
['Justin Holiday', 'holidju01'] 2
['Rondae Hollis-Jefferson', 'holliro01'] 2
['Richaun Holmes', 'holmeri01'] 2
['Rodney Hood', 'hoodro01'] 2
['Al Horford', 'horfoal01'] 2
['Danuel House', 'houseda01'] 2
['Dwight Howard', 'howardw01'] 2
['Marcelo Huertas', 'huertma01'] 2
['Josh Huestis', 'huestjo01'] 2
['Kris Humphries', 'humphkr01'] 2
['R.J. Hunter', 'hunterj01'] 2
['Serge Ibaka', 'ibakase01'] 2
['Serge Ibaka', 'ibakase01'] 2
['Serge Ibaka', 'ibakase01'] 2
['Andre Iguodala', 'iguodan01'] 2
['Ersan ƒ∞lyasova', 'ilyaser01'] 2
['Ersan ƒ∞lyasova', 'ilyaser01'] 2
['Ersan ƒ∞lyasova', 'ilyaser01'] 2
['Ersan ƒ∞lyasova', 'ilyaser01'] 2
['Joe Ingles', 'inglejo01'] 2
['Brandon Ingram', 'ingrabr01'] 2
['Kyrie Irving', 'irvinky01'] 2
['Jarrett Jack', 'jackja01'] 2
['Demetrius Jackson', 'jacksde01'] 2
['Pierre Jackson', 'jackspi01'] 2
['Reggie Jackson', 'jacksre01'] 2
['LeBron James', 'jamesle01'] 2
['Al Jefferson', 'jeffeal01'] 2
['Richard Jefferson', 'jefferi01'] 2
['John Jenkins', 'jenkijo01'] 2
['Brandon Jennings', 'jennibr01'] 2
['Brandon Jennings', 'jennibr01'] 2
['Brandon Jennings', 'jennibr01'] 2
['Jonas Jerebko', 'jerebjo01'] 2
['Amir Johnson', 'johnsam01'] 2
['Brice Johnson', 'johnsbr02'] 2
['James Johnson', 'johnsja01'] 2
['Joe Johnson', 'johnsjo02'] 2
['Stanley Johnson', 'johnsst04'] 2
['Tyler Johnson', 'johnsty01'] 2
['Wesley Johnson', 'johnswe01'] 2
['Nikola Jokiƒá', 'jokicni01'] 2
['Dahntay Jones', 'jonesda02'] 2
['Damian Jones', 'jonesda03'] 2
['Derrick Jones Jr.', 'jonesde02'] 2
['James Jones', 'jonesja02'] 2
['Terrence Jones', 'joneste01'] 2
['Terrence Jones', 'joneste01'] 2
['Terrence Jones', 'joneste01'] 2
['Tyus Jones', 'jonesty01'] 2
['DeAndre Jordan', 'jordade01'] 2
['Cory Joseph', 'josepco01'] 2
['Frank Kaminsky', 'kaminfr01'] 2
['Enes Kanter', 'kanteen01'] 2
['Ryan Kelly', 'kellyry01'] 2
['Michael Kidd-Gilchrist', 'kiddgmi01'] 2
['Sean Kilpatrick', 'kilpase01'] 2
['Brandon Knight', 'knighbr03'] 2
['Kyle Korver', 'korveky01'] 2
['Kyle Korver', 'korveky01'] 2
['Kyle Korver', 'korveky01'] 2
['Kosta Koufos', 'koufoko01'] 2
['Mindaugas Kuzminskas', 'kuzmimi01'] 2
['Skal Labissi√®re', 'labissk01'] 2
['Jeremy Lamb', 'lambje01'] 2
['Nicol√°s Laprov√≠ttola', 'laproni01'] 2
['Joffrey Lauvergne', 'lauvejo01'] 2
['Joffrey Lauvergne', 'lauvejo01'] 2
['Joffrey Lauvergne', 'lauvejo01'] 2
['Zach LaVine', 'lavinza01'] 2
['Ty Lawson', 'lawsoty01'] 2
['Jake Layman', 'laymaja01'] 2
['Courtney Lee', 'leeco01'] 2
['David Lee', 'leeda02'] 2
['Alex Len', 'lenal01'] 2
['Kawhi Leonard', 'leonaka01'] 2
['Meyers Leonard', 'leoname01'] 2
['Jon Leuer', 'leuerjo01'] 2
['Caris LeVert', 'leverca01'] 2
['DeAndre Liggins', 'liggide01'] 2
['DeAndre Liggins', 'liggide01'] 2
['DeAndre Liggins', 'liggide01'] 2
['Damian Lillard', 'lillada01'] 2
['Jeremy Lin', 'linje01'] 2
['Shaun Livingston', 'livinsh01'] 2
['Shawn Long', 'longsh01'] 2
['Kevon Looney', 'looneke01'] 2
['Brook Lopez', 'lopezbr01'] 2
['Robin Lopez', 'lopezro01'] 2
['Kevin Love', 'loveke01'] 2
['Kyle Lowry', 'lowryky01'] 2
['John Lucas III', 'lucasjo02'] 2
['Timoth√© Luwawu-Cabarrot', 'luwawti01'] 2
['Trey Lyles', 'lylestr01'] 2
['Sheldon Mac', 'mcclesh01'] 2
['Shelvin Mack', 'macksh01'] 2
['Ian Mahinmi', 'mahinia01'] 2
['Thon Maker', 'makerth01'] 2
['Boban Marjanoviƒá', 'marjabo01'] 2
['Jarell Martin', 'martija01'] 2
['Wesley Matthews', 'matthwe02'] 2
['Luc Mbah a Moute', 'mbahalu01'] 2
['James Michael McAdoo', 'mcadoja01'] 2
['Patrick McCaw', 'mccawpa01'] 2
['CJ McCollum', 'mccolcj01'] 2
['T.J. McConnell', 'mccontj01'] 2
['Chris McCullough', 'mcculch01'] 2
['Chris McCullough', 'mcculch01'] 2
['Chris McCullough', 'mcculch01'] 2
['K.J. McDaniels', 'mcdankj01'] 2
['K.J. McDaniels', 'mcdankj01'] 2
['K.J. McDaniels', 'mcdankj01'] 2
['Doug McDermott', 'mcderdo01'] 2
['Doug McDermott', 'mcderdo01'] 2
['Doug McDermott', 'mcderdo01'] 2
['JaVale McGee', 'mcgeeja01'] 2
['Rodney McGruder', 'mcgruro01'] 2
['Ben McLemore', 'mclembe01'] 2
['Jordan McRae', 'mcraejo01'] 2
['Josh McRoberts', 'mcrobjo01'] 2
['Jodie Meeks', 'meeksjo01'] 2
['Salah Mejri', 'mejrisa01'] 2
['Jordan Mickey', 'mickejo01'] 2
['Khris Middleton', 'middlkh01'] 2
['C.J. Miles', 'milescj01'] 2
['Mike Miller', 'millemi01'] 2
['Patty Mills', 'millspa02'] 2
['Elijah Millsap', 'millsel01'] 2
['Paul Millsap', 'millspa01'] 2
['Nikola Mirotiƒá', 'mirotni01'] 2
['Greg Monroe', 'monrogr01'] 2
["E'Twaun Moore", 'mooreet01'] 2
['Marcus Morris', 'morrima03'] 2
['Markieff Morris', 'morrima02'] 2
['Anthony Morrow', 'morroan01'] 2
['Anthony Morrow', 'morroan01'] 2
['Anthony Morrow', 'morroan01'] 2
['Donatas Motiej≈´nas', 'motiedo01'] 2
['Timofey Mozgov', 'mozgoti01'] 2
['Emmanuel Mudiay', 'mudiaem01'] 2
['Shabazz Muhammad', 'muhamsh01'] 2
['Dejounte Murray', 'murrade01'] 2
['Jamal Murray', 'murraja01'] 2
['Mike Muscala', 'muscami01'] 2
['Larry Nance Jr.', 'nancela02'] 2
['Shabazz Napier', 'napiesh01'] 2
['Maurice Ndour', 'ndourma01'] 2
['Gary Neal', 'nealga01'] 2
['Jameer Nelson', 'nelsoja01'] 2
['Raul Neto', 'netora01'] 2
['Georges Niang', 'niangge01'] 2
['Andrew Nicholson', 'nichoan01'] 2
['Andrew Nicholson', 'nichoan01'] 2
['Andrew Nicholson', 'nichoan01'] 2
['Joakim Noah', 'noahjo01'] 2
['Nerlens Noel', 'noelne01'] 2
['Nerlens Noel', 'noelne01'] 2
['Nerlens Noel', 'noelne01'] 2
['Lucas Nogueira', 'noguelu01'] 2
['Steve Novak', 'novakst01'] 2
['Dirk Nowitzki', 'nowitdi01'] 2
['Jusuf Nurkiƒá', 'nurkiju01'] 2
['Jusuf Nurkiƒá', 'nurkiju01'] 2
['Jusuf Nurkiƒá', 'nurkiju01'] 2
['David Nwaba', 'nwabada01'] 2
["Johnny O'Bryant", 'obryajo01'] 2
["Johnny O'Bryant", 'obryajo01'] 2
["Johnny O'Bryant", 'obryajo01'] 2
["Kyle O'Quinn", 'oquinky01'] 2
['Daniel Ochefu', 'ochefda01'] 2
['Jahlil Okafor', 'okafoja01'] 2
['Victor Oladipo', 'oladivi01'] 2
['Kelly Olynyk', 'olynyke01'] 2
['Arinze Onuaku', 'onuakar01'] 2
['Chinanu Onuaku', 'onuakch01'] 2
['Kelly Oubre Jr.', 'oubreke01'] 2
['Zaza Pachulia', 'pachuza01'] 2
['Georgios Papagiannis', 'papagge01'] 2
['Jabari Parker', 'parkeja01'] 2
['Tony Parker', 'parketo01'] 2
['Chandler Parsons', 'parsoch01'] 2
['Lamar Patterson', 'pattela01'] 2
['Patrick Patterson', 'pattepa01'] 2
['Chris Paul', 'paulch01'] 2
['Adreian Payne', 'paynead01'] 2
['Cameron Payne', 'payneca01'] 2
['Cameron Payne', 'payneca01'] 2
['Cameron Payne', 'payneca01'] 2
['Elfrid Payton', 'paytoel01'] 2
['Gary Payton II', 'paytoga02'] 2
['Paul Pierce', 'piercpa01'] 2
['Marshall Plumlee', 'plumlma02'] 2
['Mason Plumlee', 'plumlma01'] 2
['Mason Plumlee', 'plumlma01'] 2
['Mason Plumlee', 'plumlma01'] 2
['Miles Plumlee', 'plumlmi01'] 2
['Miles Plumlee', 'plumlmi01'] 2
['Miles Plumlee', 'plumlmi01'] 2
['Jakob Poeltl', 'poeltja01'] 2
['Otto Porter', 'porteot01'] 2
['Bobby Portis', 'portibo01'] 2
['Kristaps Porzi≈Üƒ£is', 'porzikr01'] 2
['Dwight Powell', 'poweldw01'] 2
['Norman Powell', 'powelno01'] 2
['Alex Poythress', 'poythal01'] 2
['Ronnie Price', 'pricero01'] 2
['Tim Quarterman', 'quartti01'] 2
['Chasson Randle', 'randlch01'] 2
['Chasson Randle', 'randlch01'] 2
['Chasson Randle', 'randlch01'] 2
['Julius Randle', 'randlju01'] 2
['Zach Randolph', 'randoza01'] 2
['J.J. Redick', 'redicjj01'] 2
['Willie Reed', 'reedwi02'] 2
['Josh Richardson', 'richajo01'] 2
['Malachi Richardson', 'richama01'] 2
['Austin Rivers', 'riverau01'] 2
['Andre Roberson', 'roberan03'] 2
['Brian Roberts', 'roberbr01'] 2
['Glenn Robinson III', 'robingl02'] 2
['Thomas Robinson', 'robinth01'] 2
['Sergio Rodr√≠guez', 'rodrise01'] 2
['Rajon Rondo', 'rondora01'] 2
['Derrick Rose', 'rosede01'] 2
['Terrence Ross', 'rosste01'] 2
['Terrence Ross', 'rosste01'] 2
['Terrence Ross', 'rosste01'] 2
['Terry Rozier', 'roziete01'] 2
['Ricky Rubio', 'rubiori01'] 2
['Damjan Rude≈æ', 'rudezda01'] 2
['Brandon Rush', 'rushbr01'] 2
["D'Angelo Russell", 'russeda01'] 2
['Domantas Sabonis', 'sabondo01'] 2
['Larry Sanders', 'sandela01'] 2
['Dario ≈†ariƒá', 'saricda01'] 2
['Tom√°≈° Satoransk√Ω', 'satorto01'] 2
['Dennis Schr√∂der', 'schrode01'] 2
['Luis Scola', 'scolalu01'] 2
['Mike Scott', 'scottmi01'] 2
['Thabo Sefolosha', 'sefolth01'] 2
['Wayne Selden', 'seldewa01'] 2
['Wayne Selden', 'seldewa01'] 2
['Wayne Selden', 'seldewa01'] 2
['Kevin S√©raphin', 'serapke01'] 2
['Ramon Sessions', 'sessira01'] 2
['Iman Shumpert', 'shumpim01'] 2
['Pascal Siakam', 'siakapa01'] 2
['Jonathon Simmons', 'simmojo02'] 2
['Kyle Singler', 'singlky01'] 2
['Marcus Smart', 'smartma01'] 2
['Ish Smith', 'smithis01'] 2
['J.R. Smith', 'smithjr01'] 2
['Jason Smith', 'smithja02'] 2
['Tony Snell', 'snellto01'] 2
['Marreese Speights', 'speigma01'] 2
['Tiago Splitter', 'splitti01'] 2
['Nik Stauskas', 'stausni01'] 2
['Lance Stephenson', 'stephla01'] 2
['Lance Stephenson', 'stephla01'] 2
['Lance Stephenson', 'stephla01'] 2
['Lance Stephenson', 'stephla01'] 2
['Jarnell Stokes', 'stokeja01'] 2
['Diamond Stone', 'stonedi01'] 2
['Rodney Stuckey', 'stuckro01'] 2
['Jared Sullinger', 'sullija01'] 2
['Edy Tavares', 'tavarwa01'] 2
['Edy Tavares', 'tavarwa01'] 2
['Edy Tavares', 'tavarwa01'] 2
['Isaiah Taylor', 'taylois01'] 2
['Jeff Teague', 'teaguje01'] 2
['Mirza Teletoviƒá', 'teletmi01'] 2
['Garrett Temple', 'templga01'] 2
['Jason Terry', 'terryja01'] 2
['Isaiah Thomas', 'thomais02'] 2
['Lance Thomas', 'thomala01'] 2
['Hollis Thompson', 'thompho01'] 2
['Hollis Thompson', 'thompho01'] 2
['Hollis Thompson', 'thompho01'] 2
['Klay Thompson', 'thompkl01'] 2
['Tristan Thompson', 'thomptr01'] 2
['Marcus Thornton', 'thornma01'] 2
['Mike Tobey', 'tobeymi01'] 2
['Anthony Tolliver', 'tollian01'] 2
['Axel Toupane', 'toupaax01'] 2
['Axel Toupane', 'toupaax01'] 2
['Axel Toupane', 'toupaax01'] 2
['Karl-Anthony Towns', 'townska01'] 2
['P.J. Tucker', 'tuckepj01'] 2
['P.J. Tucker', 'tuckepj01'] 2
['P.J. Tucker', 'tuckepj01'] 2
['Evan Turner', 'turneev01'] 2
['Myles Turner', 'turnemy01'] 2
['Beno Udrih', 'udrihbe01'] 2
['Tyler Ulis', 'ulisty01'] 2
['Jarrod Uthoff', 'uthofja01'] 2
['Jonas Valanƒçi≈´nas', 'valanjo01'] 2
['Denzel Valentine', 'valende01'] 2
['Fred VanVleet', 'vanvlfr01'] 2
['Anderson Varej√£o', 'varejan01'] 2
['Greivis V√°squez', 'vasqugr01'] 2
['Rashad Vaughn', 'vaughra01'] 2
['Noah Vonleh', 'vonleno01'] 2
['Nikola Vuƒçeviƒá', 'vucevni01'] 2
['Sasha Vujaƒçiƒá', 'vujacsa01'] 2
['Dwyane Wade', 'wadedw01'] 2
['Dion Waiters', 'waitedi01'] 2
['Kemba Walker', 'walkeke02'] 2
['John Wall', 'walljo01'] 2
['Taurean Prince', 'princta02'] 2
['T.J. Warren', 'warretj01'] 2
['C.J. Watson', 'watsocj01'] 2
['Briante Weber', 'weberbr01'] 2
['Briante Weber', 'weberbr01'] 2
['Briante Weber', 'weberbr01'] 2
['David West', 'westda01'] 2
['Russell Westbrook', 'westbru01'] 2
['Okaro White', 'whiteok01'] 2
['Isaiah Whitehead', 'whiteis01'] 2
['Hassan Whiteside', 'whiteha01'] 2
['Andrew Wiggins', 'wiggian01'] 2
['C.J. Wilcox', 'wilcocj01'] 2
['Alan Williams', 'willial03'] 2
['Deron Williams', 'willide01'] 2
['Deron Williams', 'willide01'] 2
['Deron Williams', 'willide01'] 2
['Derrick Williams', 'willide02'] 2
['Derrick Williams', 'willide02'] 2
['Derrick Williams', 'willide02'] 2
['Lou Williams', 'willilo02'] 2
['Lou Williams', 'willilo02'] 2
['Lou Williams', 'willilo02'] 2
['Marvin Williams', 'willima02'] 2
['Reggie Williams', 'willire02'] 2
['Troy Williams', 'willitr02'] 2
['Troy Williams', 'willitr02'] 2
['Troy Williams', 'willitr02'] 2
['Kyle Wiltjer', 'wiltjky01'] 2
['Justise Winslow', 'winslju01'] 2
['Jeff Withey', 'witheje01'] 2
['Christian Wood', 'woodch01'] 2
['Metta World Peace', 'artesro01'] 2
['Brandan Wright', 'wrighbr03'] 2
['Delon Wright', 'wrighde01'] 2
['James Young', 'youngja01'] 2
['Joe Young', 'youngjo01'] 2
['Nick Young', 'youngni01'] 2
['Thaddeus Young', 'youngth01'] 2
['Cody Zeller', 'zelleco01'] 2
['Tyler Zeller', 'zellety01'] 2
['Stephen Zimmerman', 'zimmest01'] 2
['Paul Zipser', 'zipsepa01'] 2
['Ivica Zubac', 'zubaciv01'] 2

In [73]:
# Split the playid and name and list the rows which are not split into 2 parts (either 1 or >2)
for name in player_id_name:
    if (len(name.split("\\")) != 2):
        print(name.split("\\"), len(name.split("\\")))

In [74]:
# adjust split argument to check whether our code wortks by changing delimeter to space
# Split the playid and name and list the rows which are not split into 2 parts (either 1 or >2)
for name in player_id_name:
    if len(name.split()) != 2:
        print(name.split(), len(name.split()))
# could see that all rows are split into 2 (not less, not more)

['Tim', 'Hardaway', 'Jr.\\hardati02'] 3
['Nen√™\\hilarne01'] 1
['Derrick', 'Jones', 'Jr.\\jonesde02'] 3
['John', 'Lucas', 'III\\lucasjo02'] 3
['Luc', 'Mbah', 'a', 'Moute\\mbahalu01'] 4
['James', 'Michael', 'McAdoo\\mcadoja01'] 3
['Larry', 'Nance', 'Jr.\\nancela02'] 3
['Kelly', 'Oubre', 'Jr.\\oubreke01'] 3
['Gary', 'Payton', 'II\\paytoga02'] 3
['Glenn', 'Robinson', 'III\\robingl02'] 3
['Metta', 'World', 'Peace\\artesro01'] 3

In [91]:
# Splits the Name Column into two columns and add it to Dataframe
split_name_df = player_stats_201617_clean_df['Player'].str.split("\\", n = 1, expand = True)
split_name_df

                     0          1
0         √Ålex Abrines  abrinal01
1           Quincy Acy    acyqu01
2           Quincy Acy    acyqu01
3           Quincy Acy    acyqu01
4         Steven Adams  adamsst01
..                 ...        ...
590        Cody Zeller  zelleco01
591       Tyler Zeller  zellety01
592  Stephen Zimmerman  zimmest01
593        Paul Zipser  zipsepa01
594        Ivica Zubac  zubaciv01

[595 rows x 2 columns]

In [92]:
split_name_df.dtypes

0    object
1    object
dtype: object

In [96]:
#Add New column called player_name
player_stats_201617_clean_df["player_name"] = split_name_df[0]
player_stats_201617_clean_df["player_id"] = split_name_df[1]

In [97]:
# Verif whether new columns are added to the Dataframe
player_stats_201617_clean_df.dtypes

Rk               int64
Player          object
Pos             object
Age              int64
Tm              object
G                int64
GS               int64
MP             float64
FG             float64
FGA            float64
FG%            float64
3P             float64
3PA            float64
3P%            float64
2P             float64
2PA            float64
2P%            float64
eFG%           float64
FT             float64
FTA            float64
FT%            float64
ORB            float64
DRB            float64
TRB            float64
AST            float64
STL            float64
BLK            float64
TOV            float64
PF             float64
PTS            float64
player_name     object
player_id       object
dtype: object

In [98]:
# writing Clean data to csv file
player_stats_201617_clean_df.to_csv(r'../../Resources/PreprocessedDataFiles/NBA Players Stats 201617_clean.csv', encoding='utf-8', header='true')