In [1]:
import pandas as pd
import os

In [2]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
os.getcwd()

'/Users/dhanaprakashdurairaj/Documents/GitHub/nba-player-analytics/Pre-processing/preprocessing_data'

In [4]:
# File to Load (Remember to change these)
player_stats_allyears_data_to_load = "../../Resources/PreprocessedDataFiles/NBAPlayersStatsAllYears.csv"
player_salary_allyears_data_to_load = "../../Resources/PreprocessedDataFiles/NBAPlayersSalaryAllYears.csv"

print(player_stats_allyears_data_to_load)
print(player_salary_allyears_data_to_load)

../../Resources/PreprocessedDataFiles/NBAPlayersStatsAllYears.csv
../../Resources/PreprocessedDataFiles/NBAPlayersSalaryAllYears.csv

In [6]:
print(os.path.isfile(player_stats_allyears_data_to_load))
print(os.path.isfile(player_salary_allyears_data_to_load))

True
True

In [7]:
# Read the Player Stat and Salary Data
player_stats_allyears_df = pd.read_csv(player_stats_allyears_data_to_load)
player_salary_allyears_df = pd.read_csv(player_salary_allyears_data_to_load)

In [8]:
# View Sats Dataframe
player_stats_allyears_df

,Unnamed: 0,Unnamed: 0.1,player_id,playing_season,playing_position,playing_age,team_name,no_of_games_played,no_minutes_played,field_goals_made,...,three_point_pctg,effective_field_goal_pctg,free_thows_made,free_throws_pctg,total_rebounds,no_of_assists,no_of_steals,no_of_blocks,no_of_turnovers,points
0,0,0,abrinal01,2016,SG,23,OKC,68,15.5,2.0,...,0.381,0.531,0.6,0.898,1.3,0.6,0.5,0.1,0.5,6.0
1,1,1,acyqu01,2016,PF,26,TOT,38,14.7,1.8,...,0.411,0.521,1.2,0.750,3.0,0.5,0.4,0.4,0.6,5.8
2,2,4,adamsst01,2016,C,23,OKC,80,29.9,4.7,...,0.000,0.571,2.0,0.611,7.7,1.1,1.1,1.0,1.8,11.3
3,3,5,afflaar01,2016,SG,31,SAC,61,25.9,3.0,...,0.411,0.514,1.4,0.892,2.0,1.3,0.3,0.1,0.7,8.4
4,4,6,ajincal01,2016,C,28,NOP,39,15.0,2.3,...,0.000,0.500,0.7,0.725,4.5,0.3,0.5,0.6,0.8,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2080,524,6242,lavinza01,2019,SG,24,CHI,60,34.8,9.0,...,0.380,0.526,4.5,0.802,4.8,4.2,1.5,0.5,3.4,25.5
2081,525,6251,norveza01,2019,SG,22,TOT,5,8.2,0.6,...,0.375,0.375,0.2,1.000,1.2,0.6,0.4,0.0,0.6,2.0
2082,526,6269,smithzh01,2019,SF,20,PHI,7,4.6,0.4,...,0.000,0.273,0.3,0.500,0.3,0.3,0.4,0.0,0.3,1.1
2083,527,6273,willizi01,2019,PF,19,NOP,24,27.8,8.8,...,0.429,0.592,4.8,0.640,6.3,2.1,0.7,0.4,2.5,22.5
2084,528,6279,cheatzy01,2019,PF,24,NOP,4,12.8,1.5,...,0.000,0.667,0.0,0.000,2.3,0.8,0.3,0.3,1.0,3.0

In [9]:
# View Salary Dataframe
player_salary_allyears_df

      Unnamed: 0  Unnamed: 0.1  player_id  playing_season     salary
0              0             0  hammoaj01          2016.0        0.0
1              1             1  brookaa01          2016.0  2700000.0
2              2             2  gordoaa01          2016.0  4351320.0
3              3             3  paynead01          2016.0  2022240.0
4              4             4  aminual01          2016.0  7680965.0
...          ...           ...        ...             ...        ...
1929         521           521  youngtr01       6273000.0     2019.0
1930         522           522  zelleco01      14471910.0     2019.0
1931         523           523  zellety01        245686.0     2019.0
1932         524           524  zizican01       2281800.0     2019.0
1933         525           525  zubaciv01       6481482.0     2019.0

[1934 rows x 5 columns]

In [12]:
player_stats_allyears_df['player_id'].value_counts()

wiggian01    4
thomais02    4
schrode01    4
hernaju01    4
wrighde01    4
            ..
ellismo01    1
siberjo01    1
munfoxa02    1
owensta01    1
morgaju01    1
Name: player_id, Length: 864, dtype: int64